main:
  - name: "About Us"
    url: "/about"
    weight: 1

  - name: "What we do"
    url: "/what_we_do"
    weight: 1

  - name: "Services"
    url: "/services"
    weight: 2

  - name: "Blog"
    url: "/blog"
    weight: 3

buttons:
  - name: "Contact Us"
    url: "/contact"
    weight: 4

footer:
  - name: "Home"
    url: "/"
    weight: 1

  - name: "About Us"
    url: "/about"
    weight: 2

  - name: "Services"
    url: "/services"
    weight: 3

  - name: "Blog"
    url: "/blog"
    weight: 4

  - name: "Contact Us"
    url: "/contact"
    weight: 5
