title: "Qim Center"
description: "Algorithms for quantitative image analysis."
images: 
  - "images/home/hero/qim-logo.png"

logo: "images/shared/qim-icon_gradient-transparent-background.png"

favicons:
  themeColor: "#FFFFFF"
  backgroundColor: "#FFFFFF"
  faviconColor: "#000000"

contact:
  - "trungkienspktnd@gamail.com"
  - "207.555.0119"

social:
  dribbble: "#"
  instagram: "#"
  facebook: "#"
  twitter: "#"

copyright: "Â© 2022 Agency Web All Rights Reserved"

colors:
  primary: "#FC7323"
  secondary: "#E63F47"